name: kabelwerk
version: 0.2.2
description: >-
  Kabelwerk is a fast and secure chat as a service for digital health
  applications. This is the Kabelwerk SDK for Dart.

homepage: https://kabelwerk.io
repository: https://github.com/kabelwerk/sdk-dart
issue_tracker: https://github.com/kabelwerk/sdk-dart/issues

dependencies:
  cross_file: ^0.3.3
  equatable: ^2.0.5
  http: ^0.13.5
  http_parser: ^4.0.0
  logging: ^1.1.0
  phoenix_socket: ^0.6.4

dev_dependencies:
  lints: ^2.0.1
  test: ^1.16.0

environment:
  sdk: '>=2.17.0 <3.0.0'
