name: kabelwerk
version: 0.0.0
description: The Kabelwerk SDK for Dart.

homepage: https://kabelwerk.io
repository: https://github.com/kabelwerk/sdk-dart
issue_tracker: https://github.com/kabelwerk/sdk-dart/issues

dependencies:
  phoenix_wings: ^1.0.2

dev_dependencies:
  args: ^2.3.0
  lints: ^1.0.0
  test: ^1.16.0

environment:
  sdk: '>=2.14.4 <3.0.0'
